[package]
name = "bruno-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = { version = "3.6.1", default-features = false }
jaq-core = "3.1.1"
jaq-json = { version = "2.0.3", features = ["serde"] }
jaq-std = "3.0.3"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm", "layout-cache", "unstable-rendered-line-info"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["process", "rt-multi-thread", "macros", "sync", "io-util", "time"] }

[target.'cfg(unix)'.dependencies]
command-fds = { version = "0.3.3", features = ["tokio"] }
